In [4]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
diabetes = pd.read_csv('Diabetes Classification.csv')
diabetes.head()

,Age,Gender,BMI,Blood Pressure,FBS,HbA1c,Family History of Diabetes,Smoking,Diet,Exercise,Diagnosis
0,45,Male,25,Normal,100,5.7,No,No,Healthy,Regular,No
1,55,Female,30,High,120,6.4,Yes,Yes,Poor,No,Yes
2,65,Male,35,High,140,7.1,Yes,Yes,Poor,No,Yes
3,75,Female,40,High,160,7.8,Yes,Yes,Poor,No,Yes
4,40,Male,20,Normal,80,5.0,No,No,Healthy,Regular,No

In [8]:
diabetes.describe()

              Age         BMI         FBS       HbA1c
count  128.000000  128.000000  128.000000  128.000000
mean    42.031250   35.359375  162.500000    7.887500
std     16.783915   14.981739   61.323975    2.146339
min     12.000000   10.000000   80.000000    5.000000
25%     28.000000   24.000000  120.000000    6.400000
50%     40.000000   34.000000  160.000000    7.800000
75%     55.000000   45.500000  205.000000    9.375000
max     75.000000   67.000000  280.000000   12.000000

In [10]:
# I dont think we need to do much feature tuning here, but lets see if we can find any correlations
# also dont think we need to do much cleaning
corr = diabetes.corr()
print(corr)

            Age       BMI       FBS     HbA1c
Age    1.000000  0.850197  0.746277  0.746277
BMI    0.850197  1.000000  0.969875  0.969875
FBS    0.746277  0.969875  1.000000  1.000000
HbA1c  0.746277  0.969875  1.000000  1.000000